### ISSUE TITLE
Merge https://github.com/clamsproject/template-repo-app-python/ into SDK

### ISSUE THREAD

**Issue by keighrim** [clamsproject/clams-python#119]
### Summary

Currently we have a separate git repository https://github.com/clamsproject/template-repo-app-python/ , whose purposes are
1. providing an app developer with a skeleton codebase for new app development 
2. providing an app developer with a cookiecutter app documentation template
3. working as a single place for holding app development documentation 

However, having a separate codebase for the starter kit turned out to be quite inefficient to keep up with updates in SDK, so I insist merge that repository as a part of the `clams-python` SDK. App developers can run a clams CLI command to create a skeleton code in current working directory, instead of cloning the template repository. 

### Related

from #117 
> 1. Is the separate "template" repository the best place to put the `metadata.py` template? If we do so, then when there's an update in the metadata scheme, we need to update two different codebase. I think that's probably not the best practice. We can maybe package the whole template repository inside the SDK and add a CLI command (like `clams new-app`) to release a local copy of the template on demand.

**Comment by keighrim** [comment]
Make sure https://github.com/clamsproject/clams-python/pull/118#issuecomment-1504214736 is included in an updated template.

**Comment by marcverhagen** [comment]
I like having a clams command to initialize a new application.
