### ISSUE TITLE
💡 `clams source --version`

### ISSUE THREAD

**Issue by mrharpo** [clamsproject/clams-python#149]
### New Feature Summary

# `source --version`
Can the CLI include a `--version` flag to specify a specific mmif version?

### Additional context

After `clams source`ing an empty mmif, I ran it through[ app-barsdetection](https://github.com/clamsproject/app-barsdetection), and it errored with:

```
"error": {
          "message": "<class 'ValueError'>: Input MMIF file (versioned: 0.5.0 is not compatible with the app targeting at 0.4.0. Make sure apps in the pipeline is all compatible. See https://mmif.clams.ai/versioning/ for information about MMIF compatibility. "
```

**Comment by keighrim** [comment]
The error no longer occurs since https://github.com/clamsproject/clams-python/pull/130. bardetection app soon will be updated to the latest SDK and the error will be gone with the update.

**Comment by keighrim** [comment]
closing the issue as a "won't fix"
