### ISSUE TITLE
Adding consumers

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-python#159]
### Because

Add common code for consumers to this repository.

Also see https://github.com/clamsproject/mmif-summarizer/issues/11.

**Comment by keighrim** [comment]
The first consumer (prototype) was `mmif-visualizer` and it was developed not only as a standalone web app, but also as a ["display application" integrated to the galaxy workflow engine](https://galaxyproject.org/admin/tools/external-display-applications-tutorial/). 

The `/display` route in the `mmif-viz` was originally designed for such integration to galaxy 

https://github.com/clamsproject/mmif-visualizer/blob/1ff27c6c48ff04b37de714719aaa5776cd8acfe8/app.py#L41-L44
https://github.com/clamsproject/wfe-galaxy/blob/dec9e60472c229efb7161c148e95e21012b74c22/make_appliance.py#L416

(but during recent updates, the route has been re-purposed, and no longer support galaxy integration)

However, given 
1. we don't have a clear answer to https://github.com/clamsproject/mmif-summarizer/issues/9 , and 
2. having a common user interface or "entry point" for all consumers DOES make a lot of sense 

I'd like to go back to the idea of using HTTP as the common interface, and want bring a common route (that any HTTP clients can call, including galaxy engine) defined in the interface.
