### ISSUE TITLE
create python + clams-python image and publish to docker hub 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/clams-python#25]
A *default* `clams-python` enabled docker image can be used as the base for many clams app images. This will enable simple `docker pull` calls or `FROM` commands in app dockerfiles.

**Comment by marcverhagen** [comment]
Yes, I would like that. Did something like that locally to avoid all those requirements being pipped during development.

**Comment by keighrim** [comment]
done via #26 and the image is published at https://hub.docker.com/repository/docker/clamsproject/clams-python
