### ISSUE TITLE
Handling missing documents

### ISSUE THREAD

**Issue by kelleyl** [clamsproject/clams-python#28]
How should apps handle missing documents? It would be nice to have some functionality in the app to check that the file paths that are being loaded exist and generate some custom exception if they don't. This would be helpful because different tools use different libraries to read files and the errors can be cryptic when the real problem is just an incorrect path. Thoughts?

**Comment by keighrim** [comment]
Yeah, good idea. I started a new branch on this issue, but this won't be fixed by next week or so.

**Comment by keighrim** [comment]
closed via #33
