### ISSUE TITLE
super method for "signing" a view

### ISSUE THREAD

**Issue by keighrim** [clamsproject/clams-python#40]
We want to have a common method in the abstract app class that *signs* a view it creates when starting annotating. That is, an app must identify itself and *sign* in the viewMetadata. To accommodate such signatures, current appMetadata scheme (0.2.2) provides `app` field. Thus all app must, at the beginning of `annotate()` method, do something like this; 

``` python
def annotate(self, mmif, params): 
    ... # validate input mmif and documents
    v = mmif.new_view()
    v.metadata.app = self.metadata.name 
    # continue
```

It would be nice if we factor that part as a method in super class. 

(Note: This issue depends on the changes to be decided at https://github.com/clamsproject/mmif/issues/153)

**Comment by marcverhagen** [comment]
I see two potential spots for that. One is to leave it to ClamsApp:

```python
def annotate(self, mmif, params): 
    # stuff
    v = mmif.new_view()
    self.sign(v)
    # more stuff
```

with `sign` being defined on ClamsApp. The other is to leave it up to mmif:

```python
def annotate(self, mmif, params): 
    # stuff
    v = mmif.new_view(self)
    # more stuff
```

where `new_view` requires or allows the app itself as an argument so it can do the signing. I prefer this one because it is shorter.

Not sure by the way what `metadata.name` is doing.

**Comment by keighrim** [comment]
(fixed typo in original comment) 
That line injects `name` from appMetadata to `app` in viewMetadata.

**Comment by marcverhagen** [comment]
Oh, duh, I get it, you do the signing in `annotate()` by just setting view metadata.

**Comment by keighrim** [comment]
Yes, it's all manual now, and implementation varies depend on the app developer (even within this small group of developers)

**Comment by keighrim** [comment]
#48 implements a basic singing method. I think it has lots of rooms to improve once we have solid input/output specs (#50, #51) laid out. Closing this for now.
