### ISSUE TITLE
interpretation of `input` list in the app metadata

### ISSUE THREAD

**Issue by keighrim** [clamsproject/clams-python#77]
This was raised in #50, but we didn't give a definitive conclusion. The question is, whether we want to interpret the list as disjunctive or conjunctive, or both. With the addition of the *optional* input types, now the issue seems to be more complex than it used to be.

#### Forced aligner example; 
Here's a FA app that accepts 1. `AudioDocument`, 2. `TextDocument` (manual transcript), 3. `TimeFrame (speech)`. It has `input` list as such 

``` json
"input": [
    { "@type": "TextDocument", "required": true },
    { "@type": "AudioDocument", "required": true },
    { "@type": "TimeFrame", 
      "required": false,
      "properties":  { "frameType": "speech" }}
]
```
In this metadata, it almost looks like that `required=true` makes those list elements conjunctive. 

Now I want to expand this app to accept `VideoDoument` as well. A new input list would be something like this; 

``` json
"input": [
    { "@type": "TextDocument", "required": true }, # still required
    { "@type": "AudioDocument", "required": ??? },
    { "@type": "VideoDocument", "required": ??? },
    { "@type": "TimeFrame", 
      "required": false,
      "properties":  { "frameType": "speech" }}
]
```
Now given the app only wants either `AudioDocument` or `VideoDocument`, not both, we don't have a good way to mark that in the `required` field.

**Comment by marcverhagen** [comment]
I think our temporary conclusion was that we could not be precise with the input specifications, but that adding a required boolean would help somewhat. We have no way of specifying that either AudioDocument or VideoDocument is required. A general solution for that would probably require the input to be a logical formula with ANDs and ORs all the way down. Or perhaps just a disjunction of conjunctions (which I though would have been enough for LAPPS).

For the second one we could have something like

```json
"input": [
    { "@type": "TextDocument" },
    { "OR": [
         { "@type": "AudioDocument" },
         { "@type": "VideoDocument" } ] },
    { "@type": "TimeFrame", 
      "required": false,
      "properties":  { "frameType": "speech" }}
]
```

The top-level is an implied AND and therefore only needs required=false to overrule that, in it is an explicit OR, we could simplify that and make it implicit

```json
"input": [
    { "@type": "TextDocument" },
    [
         { "@type": "AudioDocument" },
         { "@type": "VideoDocument" }
    ],
    { "@type": "TimeFrame", 
      "required": false,
      "properties":  { "frameType": "speech" }}
]
```

**Comment by marcverhagen** [comment]
The representation above is actually different from the conjunction of disjunctions that I mentioned on zoom earlier today. That would like like this:

```json
"input": [
    [
         { "@type": "TextDocument" },
         { "@type": "AudioDocument" },
         { "@type": "TimeFrame",  "required": false, "properties":  { "frameType": "speech" }}
    ],
    [
         { "@type": "TextDocument" },
         { "@type": "VidioDocument" },
         { "@type": "TimeFrame",  "required": false, "properties":  { "frameType": "speech" }}
    ]
]

```
