### ISSUE TITLE
Application metadata restrictions

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-python#79]
With the use of AppMetadata we have restrictions on what metadata we allow. This is both good and bad, the good part is forced consistency of metadata properties, the bad part is that app developers cannot use any other properties.

**Comment by keighrim** [comment]
We can add a kitchen sink field for anything custom properties buried in. I'm not so convinced, though, why apps need arbitrary properties, instead of having new properties promoted as a part of the *official* metadata schema (metadata schemata are all version controlled as part of `clams-python` package). Could you provide an example for such a case?

**Comment by marcverhagen** [comment]
I would say we can allow arbitrary metadata properties for the same reasons we allow arbitrary properties in annotations: other developers may find good reasons to add some property that we have not thought of in the same way as wrapped tools may create annotation properties that we do not have in our vocabulary. The latter will be more common though.

Here are two examples of properties that I would like to use that are not in the current list: something like `clams_python_version` and `mmif_python_version`, since I would like to be able to be explicit about what `clams-python` and `mmif-python` versions are assumed by the application.

Promoting some fixed set of properties is a good thing of course.

**Comment by keighrim** [comment]
Hm, good point. 

We can have something like `more` dict on the top level that developers can throw any k-v pairs in, or much easier we can simply allow `additionalProperties` at the top level. 
I think having a separate level for *custom* metadata fields will help keep metadata cleaner, so I'm voting for the former.

**Comment by keighrim** [comment]
closed by #87
